/*
rh-trex Service API

rh-trex Service API

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the SubscriptionListAllOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SubscriptionListAllOf{}

// SubscriptionListAllOf struct for SubscriptionListAllOf
type SubscriptionListAllOf struct {
	Items []Subscription `json:"items,omitempty"`
}

// NewSubscriptionListAllOf instantiates a new SubscriptionListAllOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubscriptionListAllOf() *SubscriptionListAllOf {
	this := SubscriptionListAllOf{}
	return &this
}

// NewSubscriptionListAllOfWithDefaults instantiates a new SubscriptionListAllOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubscriptionListAllOfWithDefaults() *SubscriptionListAllOf {
	this := SubscriptionListAllOf{}
	return &this
}

// GetItems returns the Items field value if set, zero value otherwise.
func (o *SubscriptionListAllOf) GetItems() []Subscription {
	if o == nil || IsNil(o.Items) {
		var ret []Subscription
		return ret
	}
	return o.Items
}

// GetItemsOk returns a tuple with the Items field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubscriptionListAllOf) GetItemsOk() ([]Subscription, bool) {
	if o == nil || IsNil(o.Items) {
		return nil, false
	}
	return o.Items, true
}

// HasItems returns a boolean if a field has been set.
func (o *SubscriptionListAllOf) HasItems() bool {
	if o != nil && !IsNil(o.Items) {
		return true
	}

	return false
}

// SetItems gets a reference to the given []Subscription and assigns it to the Items field.
func (o *SubscriptionListAllOf) SetItems(v []Subscription) {
	o.Items = v
}

func (o SubscriptionListAllOf) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SubscriptionListAllOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Items) {
		toSerialize["items"] = o.Items
	}
	return toSerialize, nil
}

type NullableSubscriptionListAllOf struct {
	value *SubscriptionListAllOf
	isSet bool
}

func (v NullableSubscriptionListAllOf) Get() *SubscriptionListAllOf {
	return v.value
}

func (v *NullableSubscriptionListAllOf) Set(val *SubscriptionListAllOf) {
	v.value = val
	v.isSet = true
}

func (v NullableSubscriptionListAllOf) IsSet() bool {
	return v.isSet
}

func (v *NullableSubscriptionListAllOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubscriptionListAllOf(val *SubscriptionListAllOf) *NullableSubscriptionListAllOf {
	return &NullableSubscriptionListAllOf{value: val, isSet: true}
}

func (v NullableSubscriptionListAllOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubscriptionListAllOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
