/*
rh-trex Service API

rh-trex Service API

API version: 0.0.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the SubscriptionPatchRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SubscriptionPatchRequest{}

// SubscriptionPatchRequest struct for SubscriptionPatchRequest
type SubscriptionPatchRequest struct {
	Foo *string `json:"foo,omitempty"`
}

// NewSubscriptionPatchRequest instantiates a new SubscriptionPatchRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSubscriptionPatchRequest() *SubscriptionPatchRequest {
	this := SubscriptionPatchRequest{}
	return &this
}

// NewSubscriptionPatchRequestWithDefaults instantiates a new SubscriptionPatchRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSubscriptionPatchRequestWithDefaults() *SubscriptionPatchRequest {
	this := SubscriptionPatchRequest{}
	return &this
}

// GetFoo returns the Foo field value if set, zero value otherwise.
func (o *SubscriptionPatchRequest) GetFoo() string {
	if o == nil || IsNil(o.Foo) {
		var ret string
		return ret
	}
	return *o.Foo
}

// GetFooOk returns a tuple with the Foo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SubscriptionPatchRequest) GetFooOk() (*string, bool) {
	if o == nil || IsNil(o.Foo) {
		return nil, false
	}
	return o.Foo, true
}

// HasFoo returns a boolean if a field has been set.
func (o *SubscriptionPatchRequest) HasFoo() bool {
	if o != nil && !IsNil(o.Foo) {
		return true
	}

	return false
}

// SetFoo gets a reference to the given string and assigns it to the Foo field.
func (o *SubscriptionPatchRequest) SetFoo(v string) {
	o.Foo = &v
}

func (o SubscriptionPatchRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SubscriptionPatchRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Foo) {
		toSerialize["foo"] = o.Foo
	}
	return toSerialize, nil
}

type NullableSubscriptionPatchRequest struct {
	value *SubscriptionPatchRequest
	isSet bool
}

func (v NullableSubscriptionPatchRequest) Get() *SubscriptionPatchRequest {
	return v.value
}

func (v *NullableSubscriptionPatchRequest) Set(val *SubscriptionPatchRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableSubscriptionPatchRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableSubscriptionPatchRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSubscriptionPatchRequest(val *SubscriptionPatchRequest) *NullableSubscriptionPatchRequest {
	return &NullableSubscriptionPatchRequest{value: val, isSet: true}
}

func (v NullableSubscriptionPatchRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSubscriptionPatchRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
