openapi: 3.0.0
info:
  description: rh-trex API
  title: rh-trex API
  version: 0.0.1
servers:
- description: current domain
  url: http://localhost:8000
- description: Main (production) server
  url: https://api.openshift.com
- description: Staging server
  url: https://api.stage.openshift.com
paths:
  /api/rh-trex/v1/dinosaurs:
    get:
      parameters:
      - description: Page number of record list when record list exceeds specified
          page size
        explode: true
        in: query
        name: page
        required: false
        schema:
          default: 1
          minimum: 1
          type: integer
        style: form
      - description: Maximum number of records to return
        explode: true
        in: query
        name: size
        required: false
        schema:
          default: 100
          minimum: 0
          type: integer
        style: form
      - description: "Specifies the search criteria. The syntax of this parameter\
          \ is\nsimilar to the syntax of the _where_ clause of an SQL statement,\n\
          using the names of the json attributes / column names of the account. \n\
          For example, in order to retrieve all the accounts with a username\nstarting\
          \ with `my`:\n\n```sql\nusername like 'my%'\n```\n\nThe search criteria\
          \ can also be applied on related resource.\nFor example, in order to retrieve\
          \ all the subscriptions labeled by `foo=bar`,\n\n```sql\nsubscription_labels.key\
          \ = 'foo' and subscription_labels.value = 'bar'\n```\n\nIf the parameter\
          \ isn't provided, or if the value is empty, then\nall the accounts that\
          \ the user has permission to see will be\nreturned."
        explode: true
        in: query
        name: search
        required: false
        schema:
          type: string
        style: form
      - description: |-
          Specifies the order by criteria. The syntax of this parameter is
          similar to the syntax of the _order by_ clause of an SQL statement,
          but using the names of the json attributes / column of the account.
          For example, in order to retrieve all accounts ordered by username:

          ```sql
          username asc
          ```

          Or in order to retrieve all accounts ordered by username _and_ first name:

          ```sql
          username asc, firstName asc
          ```

          If the parameter isn't provided, or if the value is empty, then
          no explicit ordering will be applied.
        explode: true
        in: query
        name: orderBy
        required: false
        schema:
          type: string
        style: form
      - description: |-
          Supplies a comma-separated list of fields to be returned.
          Fields of sub-structures and of arrays use <structure>.<field> notation.
          <stucture>.* means all field of a structure
          Example: For each Subscription to get id, href, plan(id and kind) and labels (all fields)

          ```
          ocm get subscriptions --parameter fields=id,href,plan.id,plan.kind,labels.* --parameter fetchLabels=true
          ```
        explode: true
        in: query
        name: fields
        required: false
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DinosaurList'
          description: A JSON array of dinosaur objects
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Auth token is invalid
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Unauthorized to perform operation
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Unexpected error occurred
      security:
      - Bearer: []
      summary: Returns a list of dinosaurs
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Dinosaur'
        description: Dinosaur data
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dinosaur'
          description: Created
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Validation errors occurred
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Auth token is invalid
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Unauthorized to perform operation
        "409":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Dinosaur already exists
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: An unexpected error occurred creating the dinosaur
      security:
      - Bearer: []
      summary: Create a new dinosaur
  /api/rh-trex/v1/dinosaurs/{id}:
    get:
      parameters:
      - description: The id of record
        explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dinosaur'
          description: Dinosaur found by id
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Auth token is invalid
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Unauthorized to perform operation
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: No dinosaur with specified id exists
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Unexpected error occurred
      security:
      - Bearer: []
      summary: Get an dinosaur by id
    patch:
      parameters:
      - description: The id of record
        explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DinosaurPatchRequest'
        description: Updated dinosaur data
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dinosaur'
          description: Dinosaur updated successfully
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Validation errors occurred
        "401":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Auth token is invalid
        "403":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Unauthorized to perform operation
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: No dinosaur with specified id exists
        "409":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Dinosaur already exists
        "500":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Unexpected error updating dinosaur
      security:
      - Bearer: []
      summary: Update an dinosaur
components:
  parameters:
    id:
      description: The id of record
      explode: false
      in: path
      name: id
      required: true
      schema:
        type: string
      style: simple
    page:
      description: Page number of record list when record list exceeds specified page
        size
      explode: true
      in: query
      name: page
      required: false
      schema:
        default: 1
        minimum: 1
        type: integer
      style: form
    size:
      description: Maximum number of records to return
      explode: true
      in: query
      name: size
      required: false
      schema:
        default: 100
        minimum: 0
        type: integer
      style: form
    search:
      description: "Specifies the search criteria. The syntax of this parameter is\n\
        similar to the syntax of the _where_ clause of an SQL statement,\nusing the\
        \ names of the json attributes / column names of the account. \nFor example,\
        \ in order to retrieve all the accounts with a username\nstarting with `my`:\n\
        \n```sql\nusername like 'my%'\n```\n\nThe search criteria can also be applied\
        \ on related resource.\nFor example, in order to retrieve all the subscriptions\
        \ labeled by `foo=bar`,\n\n```sql\nsubscription_labels.key = 'foo' and subscription_labels.value\
        \ = 'bar'\n```\n\nIf the parameter isn't provided, or if the value is empty,\
        \ then\nall the accounts that the user has permission to see will be\nreturned."
      explode: true
      in: query
      name: search
      required: false
      schema:
        type: string
      style: form
    orderBy:
      description: |-
        Specifies the order by criteria. The syntax of this parameter is
        similar to the syntax of the _order by_ clause of an SQL statement,
        but using the names of the json attributes / column of the account.
        For example, in order to retrieve all accounts ordered by username:

        ```sql
        username asc
        ```

        Or in order to retrieve all accounts ordered by username _and_ first name:

        ```sql
        username asc, firstName asc
        ```

        If the parameter isn't provided, or if the value is empty, then
        no explicit ordering will be applied.
      explode: true
      in: query
      name: orderBy
      required: false
      schema:
        type: string
      style: form
    fields:
      description: |-
        Supplies a comma-separated list of fields to be returned.
        Fields of sub-structures and of arrays use <structure>.<field> notation.
        <stucture>.* means all field of a structure
        Example: For each Subscription to get id, href, plan(id and kind) and labels (all fields)

        ```
        ocm get subscriptions --parameter fields=id,href,plan.id,plan.kind,labels.* --parameter fetchLabels=true
        ```
      explode: true
      in: query
      name: fields
      required: false
      schema:
        type: string
      style: form
  schemas:
    ObjectReference:
      properties:
        id:
          type: string
        kind:
          type: string
        href:
          type: string
      type: object
    List:
      properties:
        kind:
          type: string
        page:
          type: integer
        size:
          type: integer
        total:
          type: integer
      required:
      - items
      - kind
      - page
      - size
      - total
      type: object
    Error:
      allOf:
      - $ref: '#/components/schemas/ObjectReference'
      - $ref: '#/components/schemas/Error_allOf'
    ErrorList:
      allOf:
      - $ref: '#/components/schemas/List'
      - $ref: '#/components/schemas/ErrorList_allOf'
    Dinosaur:
      allOf:
      - $ref: '#/components/schemas/ObjectReference'
      - $ref: '#/components/schemas/Dinosaur_allOf'
    DinosaurList:
      allOf:
      - $ref: '#/components/schemas/List'
      - $ref: '#/components/schemas/DinosaurList_allOf'
    DinosaurPatchRequest:
      example:
        species: species
      properties:
        species:
          type: string
      type: object
    Error_allOf:
      properties:
        code:
          type: string
        reason:
          type: string
        operation_id:
          type: string
      type: object
      example: null
    ErrorList_allOf:
      properties:
        items:
          items:
            $ref: '#/components/schemas/Error'
          type: array
      type: object
      example: null
    Dinosaur_allOf:
      properties:
        species:
          type: string
        created_at:
          format: date-time
          type: string
        updated_at:
          format: date-time
          type: string
      type: object
      example: null
    DinosaurList_allOf:
      properties:
        items:
          items:
            $ref: '#/components/schemas/Dinosaur'
          type: array
      type: object
      example: null
  securitySchemes:
    Bearer:
      bearerFormat: JWT
      scheme: bearer
      type: http
