---
apiVersion: v1
kind: Template
name: trex-routes 
metadata:
  name: route

objects:

- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    name: trex
    labels:
      app: trex
  spec:
#    The cluster should assign a suitable host. If using CRC, it may be necessary to define one manually:
#    host: trex.apps-crc.testing
    to:
      kind: Service
      name: trex
    tls:
      termination: reencrypt
      insecureEdgeTerminationPolicy: Redirect
